FROM node:20-alpine AS builder

WORKDIR /app
RUN npm install -g pnpm

COPY package.json pnpm-lock.yaml* pnpm-workspace.yaml turbo.json tsconfig.base.json ./
COPY apps/admin/package.json ./apps/admin/
COPY packages/ ./packages/

RUN pnpm install --frozen-lockfile=false

RUN pnpm --filter "@loopin/validation" build
RUN pnpm --filter "@loopin/utils" build

COPY apps/admin/ ./apps/admin/
RUN mkdir -p apps/admin/public
RUN pnpm --filter @loopin/admin build

FROM node:20-alpine AS runner
WORKDIR /app
ENV NODE_ENV=production
RUN npm install -g pnpm

COPY --from=builder /app/package.json /app/pnpm-workspace.yaml /app/tsconfig.base.json ./
COPY --from=builder /app/node_modules ./node_modules
COPY --from=builder /app/packages ./packages
COPY --from=builder /app/apps/admin ./apps/admin

WORKDIR /app/apps/admin
EXPOSE 3001
CMD ["npm", "run", "start"]
